import { promises as fs } from "node:fs";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { PROOF_MAX_BYTES, PROOF_TYPES } from "@/lib/payment-config";

/**
 * Private storage for payment proofs. Files live OUTSIDE /public and are only ever served through
 * an authorized route. On serverless hosts with a read-only disk, point PROOF_STORAGE_DIR to a
 * persistent volume (or swap this module for S3/R2).
 */
const ROOT = process.env.PROOF_STORAGE_DIR || path.join(process.cwd(), "storage", "payment-proofs");

export async function saveProof(file: File): Promise<{ ok: true; key: string; name: string } | { ok: false; error: string }> {
  const type = PROOF_TYPES[file.type];
  if (!type) return { ok: false, error: "Format non accepté (PDF, JPG ou PNG uniquement)." };
  if (file.size === 0 || file.size > PROOF_MAX_BYTES) return { ok: false, error: "Fichier trop volumineux (5 Mo maximum)." };

  const buffer = Buffer.from(await file.arrayBuffer());
  // Verify the real content, not just the declared MIME type.
  if (!type.magic.every((byte, i) => buffer[i] === byte)) {
    return { ok: false, error: "Le contenu du fichier ne correspond pas à son format." };
  }

  await fs.mkdir(ROOT, { recursive: true });
  const key = `${randomUUID()}.${type.ext}`;
  await fs.writeFile(path.join(ROOT, key), buffer, { mode: 0o600 });
  const name = file.name.replace(/[^\w.\- ]+/g, "_").slice(0, 120) || `preuve.${type.ext}`;
  return { ok: true, key, name };
}

export async function readProof(key: string) {
  // The key is generated by us (uuid.ext); reject anything else to prevent path traversal.
  if (!/^[0-9a-f-]{36}\.(pdf|png|jpg)$/.test(key)) return null;
  try {
    return await fs.readFile(path.join(ROOT, key));
  } catch {
    return null;
  }
}

export const PROOF_MIME: Record<string, string> = { pdf: "application/pdf", png: "image/png", jpg: "image/jpeg" };
